/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  await knex('Products').del();
  await knex('Products').insert([
    {
      id: 1,
      catagoryId: 3,
      name: 'caraway',
      price: 500,
      color: 'red',
      size: 'm',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/caraway.jpeg',
      stockAmount: 50,
    },
    {
      id: 2,
      catagoryId: 2,
      name: 'Chili pepper Capsicum chinense',
      price: 500,
      color: 'yellow',
      size: 'xxl',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/capsicum-chinense.jpeg',
      stockAmount: 50,
    },
    {
      id: 3,
      catagoryId: 2,
      name: 'Chili pepper Capsicum frutescens',
      price: 500,
      color: 'red',
      size: 'l',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/Capsicum_frutescens.jpeg',
      stockAmount: 50,
    },
    {
      id: 4,
      catagoryId: 2,
      name: 'Allspice',
      price: 500,
      color: 'black',
      size: 'xl',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/allspice.jpeg',
      stockAmount: 50,
    },
    {
      id: 5,
      catagoryId: 3,
      name: 'Cumin',
      price: 500,
      color: 'yellow',
      size: 's',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/cumin.jpeg',
      stockAmount: 50,
    },
    {
      id: 6,
      catagoryId: 3,
      name: 'Fenugreek',
      price: 500,
      color: 'yellow',
      size: 's',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/fenugreek.jpeg',
      stockAmount: 50,
    },
    {
      id: 7,
      catagoryId: 3,
      name: 'Sichuan pepper',
      price: 500,
      color: 'red',
      size: 'm',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/sichuan_pepper.jpeg',
      stockAmount: 50,
    },
    {
      id: 8,
      catagoryId: 2,
      name: 'Thai long pepper',
      price: 500,
      color: 'black',
      size: 'l',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/thai-long-pepper.jpeg',
      stockAmount: 50,
    },
    {
      id: 9,
      catagoryId: 5,
      name: 'Pandan',
      price: 500,
      color: 'yellow',
      size: 'xxl',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/pandan.jpeg',
      stockAmount: 50,
    },
    {
      id: 10,
      catagoryId: 4,
      name: 'Wasabi',
      price: 500,
      color: 'black',
      size: 'xl',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/wasabi.jpeg',
      stockAmount: 50,
    },
    {
      id: 11,
      catagoryId: 2,
      name: 'Black pepper',
      price: 500,
      color: 'black',
      size: 's',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/black-pepper.jpeg',
      stockAmount: 50,
    },
    {
      id: 12,
      catagoryId: 3,
      name: 'Grains of Paradise',
      price: 500,
      color: 'brown',
      size: 's',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/grains-of-Paradis.jpeg',
      stockAmount: 50,
    },
    {
      id: 13,
      catagoryId: 4,
      name: 'Cinnamon',
      price: 500,
      color: 'brown',
      size: 'l',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/cinnamon.jpeg',
      stockAmount: 50,
    },
  ]);
};
