/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  await knex('Products').del();
  await knex('Products').insert([
    {
      id: 1,
      categoryId: 3,
      name: 'caraway',
      price: 50.0,
      size: '100',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/caraway.jpeg',
      stockAmount: 50,
    },
    {
      id: 2,
      categoryId: 2,
      name: 'Chili pepper Capsicum chinense',
      price: 50.0,
      size: '250',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/capsicum-chinense.jpeg',
      stockAmount: 50,
    },
    {
      id: 3,
      categoryId: 2,
      name: 'Chili pepper Capsicum frutescens',
      price: 50.0,
      size: '100',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/Capsicum_frutescens.jpeg',
      stockAmount: 50,
    },
    {
      id: 4,
      categoryId: 2,
      name: 'Allspice',
      price: 50.0,
      size: '250',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/Allspice.jpeg',
      stockAmount: 50,
    },
    {
      id: 5,
      categoryId: 3,
      name: 'Cumin',
      price: 50.0,
      size: '100',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/blak_cumin_seeds.jpeg',
      stockAmount: 50,
    },
    {
      id: 6,
      categoryId: 3,
      name: 'Fenugreek',
      price: 50.0,
      size: '250',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/fenugreek.jpeg',
      stockAmount: 50,
    },
    {
      id: 7,
      categoryId: 3,
      name: 'Sichuan pepper',
      price: 50.0,
      size: '100',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/sichuan_pepper.jpeg',
      stockAmount: 50,
    },
    {
      id: 8,
      categoryId: 2,
      name: 'Thai long pepper',
      price: 50.0,
      size: '250',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/thai-long-pepper.jpeg',
      stockAmount: 50,
    },
    {
      id: 9,
      categoryId: 5,
      name: 'Pandan',
      price: 50.0,
      size: '250',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/pandan.jpeg',
      stockAmount: 50,
    },
    {
      id: 10,
      categoryId: 4,
      name: 'Wasabi',
      price: 50.0,
      size: '250',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/wasabi.jpeg',
      stockAmount: 50,
    },
    {
      id: 11,
      categoryId: 2,
      name: 'Black pepper',
      price: 50.0,
      size: '100',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/black_pepper_berries.jpeg',
      stockAmount: 50,
    },
    {
      id: 12,
      categoryId: 3,
      name: 'Grains of Paradise',
      price: 50.0,
      size: '100',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/grains-of-Paradis.jpeg',
      stockAmount: 50,
    },
    {
      id: 13,
      categoryId: 4,
      name: 'Cinnamon',
      price: 50.0,
      size: '250',
      status: 'inStock',
      createdAt: knex.fn.now(),
      pictureUrl: './spice-pictures/cinnamon_sticks.jpeg',
      stockAmount: 50,
    },
  ]);
};
