/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex('products').del();
  await knex('products').insert([
    {
      category_id: 1,
      name: 'caraway',
      price: 50.0,
      color: 'red',
      size: 'm',
      status: 'in_stock',
      created_at: knex.fn.now(),
      picture: '',
      stock_amount: 50,
    },
    {
      category_id: 1,
      name: 'Chili pepper Capsicum chinense',
      price: 50.0,
      color: 'yellow',
      size: 'xxl',
      status: 'in_stock',
      created_at: knex.fn.now(),
      picture: '',
      stock_amount: 50,
    },
    {
      category_id: 1,
      name: 'Chili pepper Capsicum frutescens',
      price: 50.0,
      color: 'red',
      size: 'l',
      status: 'in_stock',
      created_at: knex.fn.now(),
      picture: '',
      stock_amount: 50,
    },
    {
      category_id: 3,
      name: 'Allspice',
      price: 50.0,
      color: 'black',
      size: 'xl',
      status: 'in_stock',
      created_at: knex.fn.now(),
      picture: '',
      stock_amount: 50,
    },
    {
      category_id: 1,
      name: 'Cumin',
      price: 50.0,
      color: 'yellow',
      size: 's',
      status: 'in_stock',
      created_at: knex.fn.now(),
      picture: '',
      stock_amount: 50,
    },
    {
      category_id: 3,
      name: 'Fenugreek',
      price: 50.0,
      color: 'yellow',
      size: 's',
      status: 'in_stock',
      created_at: knex.fn.now(),
      picture: '',
      stock_amount: 50,
    },
    {
      category_id: 3,
      name: 'Sichuan pepper',
      price: 50.0,
      color: 'red',
      size: 'm',
      status: 'in_stock',
      created_at: knex.fn.now(),
      picture: '',
      stock_amount: 50,
    },
    {
      category_id: 3,
      name: 'Thai long pepper',
      price: 50.0,
      color: 'black',
      size: 'l',
      status: 'in_stock',
      created_at: knex.fn.now(),
      picture: '',
      stock_amount: 50,
    },
    {
      category_id: 3,
      name: 'Pandan',
      price: 50.0,
      color: 'yellow',
      size: 'xxl',
      status: 'in_stock',
      created_at: knex.fn.now(),
      picture: '',
      stock_amount: 50,
    },
    {
      category_id: 3,
      name: 'Wasabi',
      price: 50.0,
      color: 'green',
      size: 'xl',
      status: 'in_stock',
      created_at: knex.fn.now(),
      picture: '',
      stock_amount: 50,
    },
    {
      category_id: 3,
      name: 'Black pepper',
      price: 50.0,
      color: 'black',
      size: 's',
      status: 'in_stock',
      created_at: knex.fn.now(),
      picture: '',
      stock_amount: 50,
    },
    {
      category_id: 3,
      name: 'Grains of Paradise',
      price: 50.0,
      color: 'brown',
      size: 's',
      status: 'in_stock',
      created_at: knex.fn.now(),
      picture: '',
      stock_amount: 50,
    },
    {
      category_id: 3,
      name: 'Cinnamon',
      price: 50.0,
      color: 'brown',
      size: 'l',
      status: 'in_stock',
      created_at: knex.fn.now(),
      picture: '',
      stock_amount: 50,
    },
  ]);
};
